# Generated by Django 6.0.6 on 2026-07-05 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='指派时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='送达时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.IntegerField(choices=[(0, '未分配'), (1, '待配送'), (2, '配送中'), (3, '已送达')], default=0, verbose_name='配送状态'),
        ),
        migrations.AddField(
            model_name='order',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='riders.rider', verbose_name='配送骑手'),
        ),
    ]
