# Generated by Django 6.0.6 on 2026-06-30 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100, verbose_name='店铺名称')),
                ('shop_logo', models.ImageField(blank=True, null=True, upload_to='merchants/logos/', verbose_name='店铺Logo')),
                ('shop_description', models.TextField(blank=True, verbose_name='店铺简介')),
                ('contact_phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='联系邮箱')),
                ('address', models.CharField(max_length=200, verbose_name='店铺地址')),
                ('is_verified', models.BooleanField(default=False, verbose_name='是否已认证')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否营业')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '商家',
                'verbose_name_plural': '商家',
            },
        ),
        migrations.CreateModel(
            name='MerchantGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='成本价')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('goods', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_goods', to='goods.goods')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='merchants.merchant')),
            ],
            options={
                'verbose_name': '商家商品',
                'verbose_name_plural': '商家商品',
            },
        ),
    ]
