# Generated by Django 6.0.6 on 2026-07-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='production_date',
            field=models.DateField(blank=True, null=True, verbose_name='生产日期'),
        ),
        migrations.AddField(
            model_name='goods',
            name='shelf_life_days',
            field=models.PositiveIntegerField(default=365, verbose_name='保质期(天)'),
        ),
    ]
