# Generated by Django 6.0.6 on 2026-07-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goods_production_date_goods_shelf_life_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='height',
            field=models.DecimalField(decimal_places=1, default=10, max_digits=6, verbose_name='高(cm)'),
        ),
        migrations.AddField(
            model_name='goods',
            name='length',
            field=models.DecimalField(decimal_places=1, default=20, max_digits=6, verbose_name='长(cm)'),
        ),
        migrations.AddField(
            model_name='goods',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=6, verbose_name='重量(kg)'),
        ),
        migrations.AddField(
            model_name='goods',
            name='width',
            field=models.DecimalField(decimal_places=1, default=15, max_digits=6, verbose_name='宽(cm)'),
        ),
    ]
